name: linting, testing, building

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.0.0 ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install node modules
        run: yarn install
      - name: build production project
        run: yarn build:prod
        if: always()
      - name: run typescript linting
        run: yarn lint:ts
        if: always()
      - name: run css linting
        run: yarn lint:scss
        if: always()
      - name: run unit tests
        run: yarn test:unit
        if: always()
      - name: build storybook
        run: yarn build:storybook
        if: always()
      - name: run screenshots tests
        run: yarn test:ui:ci
        if: always()